- docs/intro.md
- scrunch/expressions.py
- scrunch/tests/test_expressions.py
this PR converts labels in expression objects into their respective numeric value:
examples:
- `ds.exclude("gender == 'male'")`
- `ds.exclude("hobbies in ['hobby1', 'hobby2']")`
- `ds.exclude("hobbies in ('hobby1', 'hobby2')")`
- `ds.exclude("hobbies != 'hobby2'")`
> allow labels in expressions

- .travis.yml
- scrunch/datasets.py
running the test suite using python versions 3.5 and 3.6 caused the following error:
```>       for element_name, obj in self.elements.items():
E       RuntimeError: OrderedDict mutated during iteration
```
This is because items on the `self.elements` were deleted during the iteration and is not allowed for OrderedDict objects on newer python versions.
This pull request ensures all test pass on python versions 2.7, 3.4, 3.5 and 3.6.
@alejandro-rivera I saw you worked on this feature, can you confirm I'm understanding correctly the logic behind the `delete` method and my changes wouldn't cause any issue.
> Make it work with python versions 3.5 and 3.6 (tests was failing with RuntimeError)

- scrunch/datasets.py
- scrunch/expressions.py
- scrunch/tests/test_datasets.py
This PR enables the current exclude Dataset method to extend an existing exclusion filter.
usage:
`ds.exclude(<expression>, 'and'/'or')`
`ds.exclude(<expression>, extend='and'/'or')`
> Extend exclusion filters

- scrunch/datasets.py
this PR implements a Dataset merge method which enables the user to merge forks by id, name or number (see default naming: 'Fork #`1`)
i.e.:
- ds.merge(fork.id)
- ds.merge('My Fork Name')
- ds.merge(1)
- ds.merge('1')
resolves #40
> Dataset method for merging with a fork

- scrunch/expressions.py
- scrunch/tests/test_expressions.py
_sorry for the typo in the branch name_.
I've added verbose messages for all exceptions thrown by the expression parser, except for one that I'm not able to test.
@xbito can you confirm messages are fine?
> Descriptive error messages for the expression parser

- scrunch/datasets.py
- scrunch/tests/test_datasets.py
Now is possible to iterate over all elements in the dataset's order, as described in #87, see the tests I've added here: https://github.com/Crunch-io/scrunch/compare/bugfix/iterate-dataset-order?expand=1#diff-ae872301ff713c915a36ec3866811bb9
> Fixes #87: makes possible to iterate over all elements in the dataset order

- scrunch/datasets.py
- scrunch/tests/test_datasets.py
- scrunch/tests/test_recodes.py
and pass the param through to `create_single/multiple_response`
fixes #89
> `ds.create_categorical` now supports `notes`

- scrunch/__init__.py
- scrunch/tests/test_utilities.py
Allows `scrunch.get_project()` rather than `scrunch.datasets.get_project()`.
> Added get_project to __init__.py to allow scrunch.get_project.

- scrunch/datasets.py
- scrunch/expressions.py
- scrunch/tests/test_datasets.py
- scrunch/tests/test_expressions.py
Added the method as described in #111, except that the _filter_ parameter is not included and _expressions_ has was renamed to _derivation_. Sample usage: 
```python
ds.create_numeric(
alias='monthly_rent',
name='Monthly rent',
description='Rent paid per month',
notes='All UK adults',
derivation='(weekly_rent * 52) / 12'
)
```
> added ds.create_numeric

- scrunch/datasets.py
- scrunch/tests/test_datasets.py
Added a `timeout` arg to `Dataset.export()`, which is used to construct a custom `progress_tracker` to help minimize `TaskProgressTimeoutErrors`. This will default to `None` meaning there is no timeout.
> Added timeout control to Dataset.export

- scrunch/datasets.py
- scrunch/tests/test_datasets.py
fixes #131
although I first thought to remove it completely the test which failed when removing the `$` made actually sense. So I now opted for just checking if the first word is reasonable.
> only check for reasonable words with optional whitespace prepended.

- scrunch/datasets.py
- scrunch/tests/test_datasets.py
> support `before` and `after` in the Variable.move method

- scrunch/order.py
this supposes deletes are in the form:
`del ds.order['GroupA']['GroupB']` where GroupB is an empty group, otherwise it will raise a ValueError.
> Supporting delete of Groups with a dict-like behaviour del group-path

- scrunch/tests/test_datasets.py
> test_replace_values do not require a specific ordering anymore

- scrunch/categories.py
- scrunch/subentity.py
Fix for:
https://github.com/Crunch-io/scrunch/issues/133
We don't get an encoding error anymore. But the naming is still not optimal.
Output look like this now:
{u'm\xe4nnlich': <Filter: name='m?nnlich'; id='5b1fb7db05d048998d353f3f9deda8d1'>, u'gender filter': <Filter: name='gender filter'; id='b08e5f73c8ab4e0ba4536d2515600ee6'>}
Obejct name can't be anything but ascii it seems in python 2:
https://bugs.python.org/issue5876#msg195996
> Filter name encoding error

- scrunch/mutable_dataset.py
- scrunch/order.py
Fixes https://github.com/Crunch-io/scrunch/issues/161
> [OrderAPI] project order requires two reloads when a dataset was added

- scrunch/datasets.py
- scrunch/expressions.py
This method is still not working, but I can't figure why. I am sending the data just like the UI is.
> adding edit_resolution method to support changing rollup_resolution of a datetime variable

- .travis.yml
- scrunch/datasets.py
- scrunch/tests/integration/scrunch_workflow_integration_test.py
- scrunch/tests/test_datasets.py
- setup.py
- tox.ini
pandas must be an optional requirement as no all applications that uses scrunch needs pandas.
Also pandas requires numpy and having both wastes unnecessary resources when building an environment from scratch.
As soon as this is merged I'll add the corresponding instructions to the wiki for the people needing pandas.
> pandas must be an optional requirement 

- scrunch/datasets.py
- scrunch/helpers.py
- scrunch/tests/test_utilities.py
Improve `_get_dataset(…)` function so it makes less requests to crunch. If `dataset` parameter is a uuid, try loading it directly first.
When doing a `get_dataset(dsid)` it was first loading the `/datasets/` catalog, then `/datasets/{dsid}/`. It makes no sense to load the datasets catalog, specially when the user performing that task has many datasets as it makes the request really slow.
With this PR it validates if the given dataset reference is a valid uuid, and if so, it loads the dataset directly from dataset endpoint, without loading the catalog.
> Improve `_get_dataset(…)` function so it makes less requests to crunch

- .gitignore
- pytest.ini
- scrunch/cubes.py
- scrunch/tests/test_cubes.py
- setup.py
- Implement `crtabs` - a method for seamless fetching of crunch cubes
- Add `cr.cube` dependency
- Needs [this pycrunch PR](https://github.com/Crunch-io/pycrunch/pull/54) to work properly
- Needs [this cr.cube PR](https://github.com/Crunch-io/crunch-cube/pull/105) to display cubes in console nicely
> Warsaw demo

- scrunch/datasets.py
- scrunch/tests/test_utilities.py
- setup.py
This PR changes how `get_dataset` works by using the new `datasets_by_name` exact name lookup provided by the Crunch API. This prevents having to GET on `/datasets/` to fetch a dataset.
> follow `datasets_by_name` from the root to resolve by exact name match

- integration/test_folders.py
- scrunch/datasets.py
closes #339 
Additionally I enabled the corresponding test function in the integration test file which revealed the same bug without this change. And there was another test function failing on py3 due to the different behavior of `map`.
> Fix `Variable.move_to_folder`

- .travis.yml
- scrunch/datasets.py
- scrunch/tests/test_datasets.py
closes #347 
Improves precision when calculating the sum of floating point numbers.
> Use `fsum` in favor of `sum`

- scrunch/folders.py
- scrunch/tests/test_folders.py
Dataset viewers don't get the `hidden` and `trash` roots exposed. Make Scrunch detect them first.
> Check if viewers have access to hidden and trash

- scrunch/cubes.py
- scrunch/tests/test_cubes.py
Replace the deprecated `CrunchCube` object with the `Cube` one. All the methods should now be properties, which should be much easier to use.
> Fix cube usage

- scrunch/datasets.py
- scrunch/tests/test_datasets.py
When a `filter` is passed in `BaseDataset.replace_values()` ...
- `process_expr` is called
- `process_expr` calls `get_dataset_variables`
- `get_dataset_variables` calls table endpoint, setting `limit=0` parameter on the table url
- back to `replace_values`, it then executes post on table resource, which now is set to have `?limit=0`
This pull request will clear the remove the parameters from the table resource url, if filter is passed, before executing a POST, thus avoiding the 404 errors
> BaseDataset.replace_values should not include parameters when executing a POST 

- integration/test_recodes.py
- scrunch/datasets.py
- scrunch/tests/test_datasets.py
Add support for categorical `fill` variables via the `create_fill_values` method
> Add `fill` support

- integration/test_backfill.py
- integration/test_recodes.py
- scrunch/datasets.py
Add support to backfill values in a dataset using a CSV file as input.
Implements `.backfill_from_csv` method that performs all the necessary API dance to upload/join/update/delete the CSV data.
> Backfill from csv

- integration/test_backfill.py
- scrunch/datasets.py
This fix addresses a bug on backfill, that it would only overwrite values if the target column cells had `No Data` on them.
This eliminates the need for a `fill` function and replaces the column straight. This is safe because we know that they both have the exact same type given how we created the tmp dataset.
> Don't try to backfill no-data values. Honor the row expression and copy

- .github/workflows/test-and-deploy.yaml
- scrunch/categories.py
- scrunch/datasets.py
- scrunch/helpers.py
- scrunch/tests/test_datasets.py
- tox.ini
> Add category date

- integration/test_views.py
- scrunch/tests/test_views.py
- scrunch/views.py
Use the root's datasets catalog to create new views instead of the `.parent` attribute from the dataset, since it doesn't always points to a catalog that allows dataset creation.
> Use root's dataset catalog to create new views

- integration/test_dataset.py
Can't tell if there's some reason why this hasn't been fixed yet, but after returning to python dev after a month it seemed crazy we were still getting these flakes.
See https://master.ci.crint.net/blue/organizations/jenkins/Crunch-io%2Fzoom/detail/PR-7207/2/pipeline/ for example
> fix task error

- scrunch/datasets.py
- scrunch/expressions.py
- scrunch/order.py
- tox.ini
As discussed in the issues section of the `scrunch` repository [here](https://github.com/Crunch-io/scrunch/issues/449), this Pull Request attempts to make `scrunch` compatible with the Python version `3.11`.
The adjustments are made only in the modules, `dataset.py`, `order.py` & `expressions.py`.
These include version specific checks for importing methods from the `collection` module and accessing of values of the `ast.Subscript` object.
|Python version| Test Result |
|--|--|
|2.7|![image](https://github.com/Crunch-io/scrunch/assets/88078876/e94ed7b2-1b7b-420e-9e66-f2bf3dbfabb2)|
|3.6|![image](https://github.com/Crunch-io/scrunch/assets/88078876/e97b595a-3bd9-4e5f-a7f0-590ceed06f76)|
|3.11|![image](https://github.com/Crunch-io/scrunch/assets/88078876/7869b219-0d8e-4d78-b676-802f05216027)| …
> Making scrunch compatible with Python 3.11

- .github/workflows/test-and-deploy.yaml
- integration/test_dataset.py
- scrunch/tests/test_datasets.py
- setup.py
- tox.ini
Following slack conversation: https://crunch-io.slack.com/archives/C072AKYD58X/p1717521227887949
> add tests on filter with datetime variables

- scrunch/expressions.py
- scrunch/helpers.py
- scrunch/tests/test_expressions.py
issue: https://crunch-io.slack.com/archives/C072AKYD58X/p1718783086949329
> fix float cast to int/id in expressions

- scrunch/expressions.py
- scrunch/tests/test_expressions.py
Now, when running prettify on expressions that has float values that are in fact integers, the return value is the integer.
> Show integers not floats for category

- integration/test_dataset.py
- integration/test_expressions.py
The pytest.skipif decorator has the wrong condition. It is the opposite of what we want to do.
this PR is aims to fix that.
> fix pytest skipif wrong clause in integration/test_expressions

- integration/test_scripts.py
- scrunch/accounts.py
- scrunch/datasets.py
- scrunch/helpers.py
- scrunch/scripts.py
- scrunch/tests/test_accounts.py
Add `strict_subvariable_syntax` flag handler for system script + tests
> Add strict subvariable syntax handler

- scrunch/datasets.py
- scrunch/tests/test_datasets.py
The `owner` parameter of the `fork()` method allows creating a dataset fork in a defined project location.
But to make it work the `owner` parameter _always_ needs to be the Project URL e.g., `https://<company>.crunch.io/api/projects/<project_id>/`.
This often requires the user, an additional step, to manually find out the project URL to pass as the `owner` parameter.
It is comparatively easier to work with the project folder paths e.g., `"Client datasets | Projects A | Project A - 1 "` than the project URL, which also is more human friendly.
Hence, this Pull Request adds a new feature to `fork()` method to allow the user to pass the project path to the `owner` parameter as well, as requested in the [issue](https://github.com/Crunch-io/scrunch/issues/464).
The previous functionality of …
> Allowing Project Paths to be passed to scrunch.dataset.fork() method

- setup.py
In this PR, we've removed the version pinning for `request` library in order to be able to use it's latest version.
> Removing version pinning for requests library

- integration/test_backfill.py
- integration/test_dataset.py
- integration/test_expressions.py
- integration/test_folders.py
- integration/test_projects.py
- integration/test_recodes.py
- integration/test_scripts.py
- integration/test_views.py
- scrunch/datasets.py
a temp folder for temp ds creation. Also, update integration tests
https://www.pivotaltracker.com/n/projects/2172644/stories/188703975
> Update integration tests to include project in payload
