scrunch/__init__.py

removed connect_with_token

---

scrunch/datasets.py

changed so you can only provide True or False (default is False).
True will set current user as editor.

Add change editor to get dataset

---

scrunch/datasets.py

I opened this PR in case we want a different output.
resolves #17

Special methods

---

scrunch/datasets.py
scrunch/tests/test_datasets.py
scrunch/tests/test_recodes.py

removes the use of `get_dataset` in the Variable classmethods
resolves #27

Fix variable methods

---

scrunch/expressions.py
scrunch/tests/integration/scrunch_workflow_integration_test.py

WIP
Make the integration tests honor the newer versions of scrunch (new rules and function signatures).

Fix integration tests

---

scrunch/categories.py
scrunch/datasets.py
scrunch/helpers.py
scrunch/tests/test_categories.py
scrunch/tests/test_datasets.py

resolves #38 for
- Dataset
- Variable
- Category

Protect attributes

---

scrunch/datasets.py
scrunch/tests/test_datasets.py

fixed this ticket: https://github.com/Crunch-io/scrunch/issues/51

Add metadata to scrunch's ds.export()

---

scrunch/tests/test_datasets.py

Test fork merges

---

scrunch/datasets.py
scrunch/tests/crunch_test.ini
scrunch/tests/test_utilities.py

This feature is an approach to solve:
https://yougov.fogbugz.com/f/cases/46610/Access-to-subvariables
The behaviour is documented at: https://docs.google.com/document/d/1tnk_kPzsyWgSbXAyi1m5v17LG3t6L0OuzUgPGiqJrUQ/edit#heading=h.91c810lm76al

Adding subvariable iteration

---

pytest.ini
scrunch/variables.py

Last week I fixed the testsuite to make it work again on travis, also fixed a failing test. Merge test into master so both branches are passing on travis again.

Merge changes from dev into master

---

scrunch/datasets.py
setup.py

This PR introduces support the `CrunchBox`:
usage:
```
>>> var1 = ds['var1_alias']
>>> f = ds.filters['f1_name']
>>> box = ds.create_crunchbox('title', 'header', 'footer', 'notes', filters=[f, 'f2_name'], variables=[var1, 'var2_alias'])
>>> ds.crunchboxes
[<CrunchBox title="..." ...>, ...]
>>> box.id
...
>>> box.widget_url
https://...
>>> box.iframe(logo=None, dimensions=None)
<figure ...></figure><iframe...
>>> box.variables
[<Variables XY>, ...]
>>> box.filters
[<Filter XY, ...>, ...]
>>> ds.delete_crunchbox(**kwargs)  # i.e. ds.delete_crunchbox(id=box.id) or
>>> box.remove()
```
@jjdelc: the boxdata entity was a bit different; I hope the docstring and comments on the proposal help understand some of my decisions.

CrunchBox support

---

scrunch/datasets.py
scrunch/tests/test_datasets.py

solves: https://github.com/Crunch-io/scrunch/issues/132

fixes issue 132, It allows creation of empty groups

---

scrunch/datasets.py
scrunch/tests/test_datasets.py

added support to `integrate` derived variables

---

scrunch/datasets.py
scrunch/tests/integration/scrunch_workflow_integration_test.py
scrunch/tests/test_datasets.py

as described in #165, with this PR I'm adding the abilities to set and retrieve missing rules for a given variable.

For #165 added ability to manage missing rules for a variable

---

scrunch/datasets.py
scrunch/tests/integration/scrunch_workflow_integration_test.py
scrunch/tests/test_datasets.py

@jamesrkg: notifying on changes.

Variable missing rules now behave like a dictionary, [case 173]

---

scrunch/datasets.py
scrunch/tests/integration/scrunch_workflow_integration_test.py

For #164, added the following methods:
- variable.set_geodata_view()
- variable.unset_geodata_view()
Is a work in progress, needs to document and make it better.

WIP: set/unset geodata view on a variable

---

scrunch/tests/test_utilities.py

added some tests that proves that this issue is not an issue with scrunch:
https://github.com/Crunch-io/scrunch/issues/213

added missing tests for Path in order.py

---

scrunch/order.py
scrunch/tests/test_utilities.py

This fixes:
https://github.com/Crunch-io/scrunch/issues/213

Path now works with python 2

---

scrunch/datasets.py

Fixes:
https://github.com/Crunch-io/scrunch/issues/211

added feature to remove weights

---

scrunch/datasets.py

Fixes:
https://github.com/Crunch-io/scrunch/issues/219

fixed ds.fork encoding problem

---

scrunch/datasets.py
scrunch/mutable_dataset.py

create_variable required _validate_vartypes

moved _validate_vartypes as well

---

integration/test_recodes.py

https://www.pivotaltracker.com/n/projects/931610/stories/155038515
row ordering is no longer guaranteed during streaming

https://www.pivotaltracker.com/n/projects/931610/stories/155038515 (mongo streaming)

---

scrunch/__init__.py
scrunch/datasets.py
scrunch/session.py
scrunch/tests/integration/scrunch_workflow_integration_test.py
scrunch/tests/test_utilities.py
scrunch/version.py
setup.py

Make Scrunch report its own user agent and not Pycrunch's

Use custom session class with custom user agent

---

scrunch/datasets.py

fixes reload og variables as jamie wants here: https://github.com/Crunch-io/scrunch/issues/265

added reload variables after deletion of a variable

---

scrunch/datasets.py
scrunch/mutable_dataset.py
scrunch/tests/test_datasets.py

fixing this issue:
https://github.com/Crunch-io/scrunch/issues/261

compare_dataset() - request for a new feature

---

scrunch/datasets.py
scrunch/tests/test_datasets.py

Fixes: https://github.com/Crunch-io/scrunch/issues/263

Add new category

---

scrunch/datasets.py
scrunch/tests/test_datasets.py

https://www.pivotaltracker.com/story/show/158676228

Clients should send "weight" in POST/PUT crunchbox

---

integration/test_projects.py
scrunch/datasets.py
scrunch/tests/mock_session.py
scrunch/tests/test_projects.py

This branch adds an integration test to run on Crunch CI to replicate a couple of bugs.
Also updates the unit tests for this behavior.

Test moving datasets

---

scrunch/datasets.py
scrunch/tests/test_projects.py

.children and .delete()

---

.travis.yml
scrunch/datasets.py
scrunch/helpers.py
scrunch/tests/integration/scrunch_workflow_integration_test.py
scrunch/tests/test_datasets.py
scrunch/tests/test_teams.py
scrunch/tests/test_utilities.py
setup.py
tox.ini

Members edits

---

scrunch/datasets.py
scrunch/tests/test_utilities.py

https://github.com/Crunch-io/scrunch/issues/296

get_project targeting nested project

---

scrunch/cubes.py
scrunch/tests/test_cubes.py

crtabs now passes on weight, filter and measures

support for more args passed

---

scrunch/folders.py
scrunch/tests/test_folders.py

use `str` in py3 instead of basestring

---

scrunch/datasets.py

fixes:
https://github.com/Crunch-io/scrunch/issues/341

added self._reload_variables() at the end of load_savepoint

---

.travis.yml

From what I can read from this:
https://pypi.org/help/#apitoken
Then this should be the right way to set it up.

removed jaraco as user and added myself

---

integration/test_folders.py
scrunch/folders.py

Remove feature flag checking for variable folders. They're always enabled in the API

Always folders

---

integration/test_recodes.py

Revert "for recodes test, column order doesn't matter."

---

scrunch/categories.py
scrunch/tests/integration/scrunch_workflow_integration_test.py
scrunch/tests/test_categories.py

Add support for editing the `date` field on categoricals

---

integration/test_backfill.py
scrunch/datasets.py

This PR temporarily removes the exclusion filter on the dataset during the backfill process.

Backfill w excl

---

.github/workflows/test-and-deploy.yaml
integration/test_scripts.py
scrunch/datasets.py
scrunch/scripts.py
scrunch/tests/mock_session.py
scrunch/tests/test_scripts.py

Adds support for executing Crunch Automation scripts on Scrunch under:
```
dataset.scripts.execute()
```

Dataset scripts

---

integration/fixtures.py

Crunch's `combine_responses` function now returns a logical array so values are always 0, 1, -1

Fix combine responses 177708292

---

integration/fixtures.py

Do not merge yet - Needs Crunch app updates.

`combine_responses` now always returns logical variable

---

tox.ini

to tackle this issue: https://github.com/Crunch-io/scrunch/issues/422

add tests for python 3.8 and 3.9

---

.github/workflows/test-and-deploy.yaml
integration/fixtures.py
integration/test_accounts.py
integration/test_backfill.py
integration/test_dataset.py
integration/test_expressions.py
integration/test_folders.py
integration/test_projects.py
integration/test_recodes.py
integration/test_scripts.py
integration/test_views.py
pytest.ini
scrunch/datasets.py
scrunch/expressions.py
scrunch/tests/conftest.py
scrunch/tests/test_datasets.py
scrunch/tests/test_expressions.py
scrunch/tests/test_recodes.py
scrunch/version.py
setup.py
tox.ini

This PR includes changes from:
- #458 
- #457 
- #456 
- #455 
The idea is to have them in a single PR that is going to be the one with all the changes and with the code for the next release.

0.18 fixes
